target-version = "py314"
line-length = 100

[lint]
select = [
    "F",      # Pyflakes
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "I",      # isort
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "SIM",    # flake8-simplify
    "TC",    # flake8-type-checking
    "RUF",    # Ruff-specific rules
    "PT",     # flake8-pytest-style
    "PIE",    # flake8-pie
    "PERF",   # Perflint
]
extend-safe-fixes = [
    "TC",  # Move imports inside/outside TYPE_CHECKING blocks
    "UP",  # Update syntaxes for current Python version recommendations
]
